<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>Hellfire.Sim</RootNamespace>
    <AssemblyName>Hellfire.Sim</AssemblyName>
  </PropertyGroup>

</Project>
