<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>Hellfire.Tools</RootNamespace>
    <AssemblyName>Hellfire.Harness</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../sim/Sim.csproj" />
  </ItemGroup>

</Project>
